#!/bin/bash

# Add the current environment's exports to /home/staging/.bashrc
# env | sed 's/^/export /' >> /home/staging/.bashrc

cat > /home/staging/.docker_env <<- EOM
export PORT=$PORT
export RELX_REPLACE_OS_VARS=true
export GITHUB_TOKEN=$GITHUB_TOKEN
EOM

chown staging:staging /home/staging/.docker_env

# Run sshd daemon to support hot delivery of new releases without
# requiring new docker container deployment.
/usr/sbin/sshd -D